name: "Publish"
on:
  workflow_dispatch:
jobs:
  release:
    name: "Pack & Upload"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: release.yaml
        name: distribution

    - uses: haskell-actions/hackage-publish@v1
      with:
        hackageToken: ${{ secrets.HACKAGE }}
        packagesPath: '.'
        docsPath: '.'
        publish: true
